#
# Macro file of "exampleB3.cc"
# To be run preferably in batch, without graphics:
# % exampleB3 run3.mac
#
#/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0
#
/run/initialize
#
/control/verbose 2
#
/run/beamOn 40000
#
# change beta source
#
/gun/particle ion
#/gun/ion 6 11
/gun/ion 11 22
#
/analysis/setFileName scoring2
/run/printProgress 100000
#/run/beamOn 40000
/run/beamOn 1000000
